version: "3.7"

services:
  react-meal-planner:
    container_name: react-meal-planner
    build: .
    ports:
      - 8085:3000
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true